on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    name: build and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Install project
        run: npm install

      - name: Run eslint & prettier
        run: npm run lint

      - name: Build with tsc
        run: npm run build

      - name: Run tests
        run: npm test
